/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTimeEntriesRouteImport } from './routes/_app/time-entries'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRenewalsRouteImport } from './routes/_app/renewals'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppImportExportRouteImport } from './routes/_app/import-export'
import { Route as AppEmailTemplatesRouteImport } from './routes/_app/email-templates'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCredentialsRouteImport } from './routes/_app/credentials'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppBackupRouteImport } from './routes/_app/backup'
import { Route as AppAmcRouteImport } from './routes/_app/amc'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeEntriesRoute = AppTimeEntriesRouteImport.update({
  id: '/time-entries',
  path: '/time-entries',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppImportExportRoute = AppImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailTemplatesRoute = AppEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppAmcRoute = AppAmcRouteImport.update({
  id: '/amc',
  path: '/amc',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amc': typeof AppAmcRoute
  '/backup': typeof AppBackupRoute
  '/clients': typeof AppClientsRoute
  '/credentials': typeof AppCredentialsRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-templates': typeof AppEmailTemplatesRoute
  '/import-export': typeof AppImportExportRoute
  '/people': typeof AppPeopleRoute
  '/renewals': typeof AppRenewalsRoute
  '/settings': typeof AppSettingsRoute
  '/time-entries': typeof AppTimeEntriesRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/amc': typeof AppAmcRoute
  '/backup': typeof AppBackupRoute
  '/clients': typeof AppClientsRoute
  '/credentials': typeof AppCredentialsRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-templates': typeof AppEmailTemplatesRoute
  '/import-export': typeof AppImportExportRoute
  '/people': typeof AppPeopleRoute
  '/renewals': typeof AppRenewalsRoute
  '/settings': typeof AppSettingsRoute
  '/time-entries': typeof AppTimeEntriesRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/amc': typeof AppAmcRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/credentials': typeof AppCredentialsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/email-templates': typeof AppEmailTemplatesRoute
  '/_app/import-export': typeof AppImportExportRoute
  '/_app/people': typeof AppPeopleRoute
  '/_app/renewals': typeof AppRenewalsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/time-entries': typeof AppTimeEntriesRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/amc'
    | '/backup'
    | '/clients'
    | '/credentials'
    | '/dashboard'
    | '/email-templates'
    | '/import-export'
    | '/people'
    | '/renewals'
    | '/settings'
    | '/time-entries'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/amc'
    | '/backup'
    | '/clients'
    | '/credentials'
    | '/dashboard'
    | '/email-templates'
    | '/import-export'
    | '/people'
    | '/renewals'
    | '/settings'
    | '/time-entries'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/amc'
    | '/_app/backup'
    | '/_app/clients'
    | '/_app/credentials'
    | '/_app/dashboard'
    | '/_app/email-templates'
    | '/_app/import-export'
    | '/_app/people'
    | '/_app/renewals'
    | '/_app/settings'
    | '/_app/time-entries'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time-entries': {
      id: '/_app/time-entries'
      path: '/time-entries'
      fullPath: '/time-entries'
      preLoaderRoute: typeof AppTimeEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/renewals': {
      id: '/_app/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AppRenewalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-export': {
      id: '/_app/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AppImportExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-templates': {
      id: '/_app/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AppEmailTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials': {
      id: '/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/amc': {
      id: '/_app/amc'
      path: '/amc'
      fullPath: '/amc'
      preLoaderRoute: typeof AppAmcRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAmcRoute: typeof AppAmcRoute
  AppBackupRoute: typeof AppBackupRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailTemplatesRoute: typeof AppEmailTemplatesRoute
  AppImportExportRoute: typeof AppImportExportRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppRenewalsRoute: typeof AppRenewalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimeEntriesRoute: typeof AppTimeEntriesRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmcRoute: AppAmcRoute,
  AppBackupRoute: AppBackupRoute,
  AppClientsRoute: AppClientsRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailTemplatesRoute: AppEmailTemplatesRoute,
  AppImportExportRoute: AppImportExportRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimeEntriesRoute: AppTimeEntriesRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
